### ISSUE TITLE
Incompatible with SUMO 1.0.x

### ISSUE THREAD

**Issue by danvk** [sidewalklabs/sumo-web3d#10]
SUMO-Web3D works with SUMO 0.32 but not with the 1.0.x. series.

The culprit is probably in this section of TraCI changes:
http://sumo.dlr.de/wiki/ChangeLog#Other_3

cc @uwmyuan @katzdave

**Comment by uwmyuan** [comment]
@danvk Thanks for the clue. 
The possible solution to replace the space between filenames with comma in each `*.sumocfg` file such as [here](https://github.com/sidewalklabs/sumo-web3d/blob/026303fdbb8bcf7b3e8669f95dffef015e07fa91/sumo_web3d/scenarios/bologna-acosta-joined/run.sumo.cfg#L7-L8).
