### ISSUE TITLE
TypeError: getSubscriptionResults() missing 1 required positional argument: 'objectID'

### ISSUE THREAD

**Issue by ysm0622** [sidewalklabs/sumo-web3d#12]
![image](https://user-images.githubusercontent.com/18487241/48053701-aca8a680-e1ee-11e8-95bb-9b94a03588cd.png)

`TypeError: getSubscriptionResults() missing 1 required positional argument: 'objectID'`

I got this error, but I cannot resolve it.

The initial frontend work well, but it doesn't simulate anything(vehicles, pedestrians)

![image](https://user-images.githubusercontent.com/18487241/48054045-98b17480-e1ef-11e8-8cf7-9c8b0eb21b49.png)

Can help?

## Environment
Ubuntu 16.04 (Docker image)
sumo-1.0.1
$SUMO_HOME set to `/~~~/sumo-1.0.1/`

I followed [this](http://sumo.dlr.de/wiki/Installing/Linux_Build#Installing_the_SUMO_binaries) instructions

**Comment by ysm0622** [comment]
I resolved it.

**Comment by danvk** [comment]
Hi @ysm0622, glad you got sumo-web3d to work! How'd you resolve this issue?
