### ISSUE TITLE
Sumo-web3d loads a blank screen for one configuration file

### ISSUE THREAD

**Issue by eugenevinitsky** [sidewalklabs/sumo-web3d#15]
Hi,

I am able to get sumo-web3d to work on all of my sumo config files but for reasons unknown it fails silently on the last one. 
The screen looks like so: 
![image](https://user-images.githubusercontent.com/7660397/48580385-ea36bf00-e8d3-11e8-8afc-4436af9ddf27.png)
The relevant config files are attached. I'm really not sure what is happening, nor can I trace the error so any help is appreciated!

[cfg.zip](https://github.com/sidewalklabs/sumo-web3d/files/2586977/cfg.zip)

**Comment by eugenevinitsky** [comment]
Note, there's nothing wrong (as far as I can tell) with the underlying cfg file. I can open it in sumo-gui and it looks like so:
![image](https://user-images.githubusercontent.com/7660397/48580681-b6a86480-e8d4-11e8-9423-07cd7cba3549.png)

**Comment by danvk** [comment]
Any errors in your javascript console?

**Comment by eugenevinitsky** [comment]
My terminal just freezes after printing: "Switching to bay-bridge-toll-20181115-1112321542309152.090739.sumo.cfg"

Is there some way to get the javascript errors?

**Comment by eugenevinitsky** [comment]
Oh here it is. Didn't know about this console before, very helpful!
Failed to load resource: the server responded with a status of 404 (Not Found)
initialization.ts:116 Request for settings 404'd.
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 13.55810546875ms
three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 10.930908203125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 10.108154296875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.957763671875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.951171875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.718994140625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.802978515625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.73095703125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 4.387939453125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.632080078125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.77099609375ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.019775390625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 4.085205078125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 4.349853515625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.0068359375ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.1240234375ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 4.001220703125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.177978515625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.95263671875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.705810546875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.7548828125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.4228515625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.889892578125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.0078125ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.546875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 5.46875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 4.758056640625ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.466796875ms
7three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 3.272216796875ms
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2
three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 7.802001953125ms
three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 6.053955078125ms
three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 13.22314453125ms
three.js:43344 THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
set @ three.js:43344
index.js:658 OBJLoader: 46.98681640625ms
initialization.ts:165 Loaded static resources in  1466.0999999614432  ms.
three.js:20919 THREE.WebGLRenderer 87
index.tsx:40 TypeError: Cannot read property 'length' of null
    at Object.triangulateShape (three.js:26925)
    at addShape (three.js:28429)
    at new ShapeBufferGeometry (three.js:28370)
    at new ShapeGeometry (three.js:28331)
    at flatMeshFromVertices (three-utils.ts:133)
    at Object.flatRectMesh (three-utils.ts:146)
    at Object.makeStaticObjects (network.ts:374)
    at new Sumo3D (sumo3d.ts:154)
    at Object.createStore [as default] (datastore.ts:52)
    at Object.<anonymous> (index.tsx:11)

index.tsx:40 TypeError: Cannot read property 'length' of null
    at Object.triangulateShape (three.js:26925)
    at addShape (three.js:28429)
    at new ShapeBufferGeometry (three.js:28370)
    at new ShapeGeometry (three.js:28331)
    at flatMeshFromVertices (three-utils.ts:133)
    at Object.flatRectMesh (three-utils.ts:146)
    at Object.makeStaticObjects (network.ts:374)
    at new Sumo3D (sumo3d.ts:154)
    at Object.createStore [as default] (datastore.ts:52)
    at Object.<anonymous> (index.tsx:11)

**Comment by eugenevinitsky** [comment]
Replaced by issue #16.

**Comment by datafilik** [comment]
Hi,
when I run sumo-web3d and point my browser to local host at port 5000, I get the blank page with the word 'loading...'.
From the web console in Firefox, the problem appears  to do with a 

> failure to _load index.bundle.js_

 and also something to do with 

> index.bundle.js being loaded with the MIME type plain/text which it doesn't regard as a valid JavaScript MIME type.


please does anyone have any idea how I could resolve this.
I have attached screenshots below
![Screenshot from 2019-04-01 18-18-44](https://user-images.githubusercontent.com/18663485/55346867-5abd3180-54ab-11e9-8134-b4a9fd4111c2.png)
![Screenshot from 2019-04-01 18-14-55](https://user-images.githubusercontent.com/18663485/55346870-5db82200-54ab-11e9-88fe-4f3e524f61c2.png)
